Pearson and Spearman correlation with restricted permutation: SP_Correlation/SP_Correlation/functions.c File Reference
SP_Correlation/SP_Correlation/functions.c File Reference
#include <stdio.h>
#include "functions.h"
#include <stdlib.h>
#include <math.h>
#include <assert.h>
Defines
#define VERBOSE false
Functions
float * allocateArrayOfFloats (int howmany)
float ** allocateArrayOfArraysOfFloats (int howmany)
int * allocateArrayOfInts (int howmany)
Field ** allocateArrayOfFields (int howmany)
int randInRange (int lo, int hi)
Generate random number in a given range.
bool inOrder (float l, float r)
Check if inputs are in desired order.
void swapF (float *l, float *r)
Exchange contents of two float variables.
void swapI (int *l, int *r)
Exchange contents of two int variables.
Perm * allocatePermutation (void)
Perm * makePerm (int size, int seed)
Creates a permutation of a given size.
void modifyPermPermutify (Perm *thePerm, int seed)
Change a permutation.
Field * allocateField (void)
Field * makeRandomField (int samples)
Create a symmetric Field with random data.
Field * makeFieldFromTDV (const char *filename)
Load a tab-delimited-value file into a Field.
void saveFieldToTDV (const char *filename, Field *theField)
Save field data to file.
void saveFieldToHTML (const char *filename, Field *theField)
Save field data to file.
void displayField (Field *theField)
Display field data on screen.
Landscape * allocateLandscape (void)
Landscape * makeLandscapeFromTDVs (int files, const char *filenames[])
bool isInLowerDiagonal (int i, int j)
void modifyLandscapeMeanify (Landscape *theData)
void modifyLandscapeRankify (Landscape *theData)
CorrelationAggregate * allocateCA (void)
void initializeCA (CorrelationAggregate *theCA)
Initialize a correlation aggregate.
void augmentCAByValues (CorrelationAggregate *theCA, float xmxbar, float ymybar)
Add data to a correlation aggregate.
float finishCorrelation (CorrelationAggregate *theCA)
Extract result from correlation aggregate.
void augmentCAByFields (CorrelationAggregate *theCA, Field *X, Field *Y)
Augment a correlation aggregate with information from two fields.
float mantelR (Landscape *mPreserved, Landscape *mPermuted, CorrelationAggregate *theCA)
Find correlation of two sets of fields.
float mantelRPartial (Landscape *mPermuted, Landscape *mPreserved, Landscape *mGiven, CorrelationAggregate *theCA)
StatisticalData * allocateStatData (void)
StatisticalData * correlateAndFindP (Landscape *lPermuted, Landscape *lPreserved, int trials)
Run input data through multiple correlations.
StatisticalData * correlatePartialAndFindP (Landscape *lPermuted, Landscape *lPreserved, Landscape *lGiven, int trials)
void saveData (StatisticalData *dataToSave, int timestamp)
Saves statistical data to file.
void processFilePairs (int trials, int filesets, const char *argv[], int timestamp)
Creates files containing data on Spearman and Person correlation of inputs.
void processFileTriples (int trials, int filesets, const char *argv[], int timestamp)
List * allocateList (void)
List * makeListFromList (List *theData)
Create a List by copying another list.
void displayList (List *theData)
Display a list on screen.
void saveListToTDV (const char *filename, List *theData)
Output a list to file.
void modifyListMeanify (List *theData)
Center a list about its mean.
void modifyListSortify (List *theData)
Sort a list (heapsort)
void heapSortSiftDown (List *theData, int root, int bottom)
Utility function for sorting.
rankAndCount * allocateRankAndCount (void)
rankAndCount * computeRankInList (float datum, List *theData, rankAndCount *theRank)
List * makeListFromLandscape (Landscape *theData)
Flatten a 2D field to a 1D list.
Detailed Description
Author:
Bryant Adams
Date:
3/20/12
Definition in file functions.c.
Define Documentation
#define VERBOSE false
Definition at line 14 of file functions.c.
Referenced by augmentCAByFields().
Function Documentation
float** allocateArrayOfArraysOfFloats (int howmany)
Definition at line 23 of file functions.c.
Referenced by makeFieldFromTDV(), and makeRandomField().
{
    return malloc(howmany * sizeof(float*));
}
Field ** allocateArrayOfFields (int howmany)
Definition at line 34 of file functions.c.
Referenced by makeLandscapeFromTDVs().
{
    return malloc(howmany * sizeof(Field));
}
float* allocateArrayOfFloats (int howmany)
Definition at line 18 of file functions.c.
Referenced by correlateAndFindP(), correlatePartialAndFindP(), makeFieldFromTDV(), makeListFromLandscape(), makeListFromList(), makeRandomField(), and makeTestList().
{
    return malloc(howmany * sizeof(float));
}
int* allocateArrayOfInts (int howmany)
Definition at line 28 of file functions.c.
Referenced by makePerm(), and testMakePerm().
{
    return malloc(howmany * sizeof(int));
}
CorrelationAggregate* allocateCA (void)
Definition at line 465 of file functions.c.
Referenced by correlateAndFindP(), correlatePartialAndFindP(), mantelR(), mantelRPartial(), testAugmentCAByValues(), testFinishCorrelation(), and testInitializeCA().
{
    return malloc(sizeof(CorrelationAggregate));
}
Field* allocateField (void)
Definition at line 135 of file functions.c.
Referenced by makeFieldFromTDV(), and makeRandomField().
{
    return malloc(sizeof(Field));
}
Landscape* allocateLandscape (void)
Definition at line 291 of file functions.c.
Referenced by makeLandscapeFromTDVs().
{
    return malloc(sizeof(Landscape));
}
List* allocateList (void)
Definition at line 792 of file functions.c.
Referenced by correlateAndFindP(), correlatePartialAndFindP(), makeListFromLandscape(), makeListFromList(), and makeTestList().
{
    return malloc(sizeof(List));
}
Perm* allocatePermutation (void)
Definition at line 79 of file functions.c.
Referenced by makePerm().
{
    return malloc(sizeof(Perm));
}
rankAndCount* allocateRankAndCount (void)
Definition at line 918 of file functions.c.
Referenced by computeRankInList().
{
    return malloc(sizeof(rankAndCount));
}
StatisticalData* allocateStatData (void)
Definition at line 597 of file functions.c.
Referenced by correlateAndFindP(), and correlatePartialAndFindP().
{
    return malloc(sizeof(StatisticalData));
}
void augmentCAByFields (CorrelationAggregate * theCA, Field * X, Field * Y)
Augment a correlation aggregate with information from two fields.
Parameters:
X First field to correlate
Y Second field to correlate
theCA Correlation aggregate to store cumulative information
Returns:
the correlation so far, which may not be the final result
Side Effects:
Adds correlation information from fields X and Permute(Y) to theCA
Definition at line 497 of file functions.c.
References augmentCAByValues(), CorrelationAggregate::denominatorL, CorrelationAggregate::denominatorR, displayField(), Field::element, Perm::index, isInLowerDiagonal(), CorrelationAggregate::numerator, Field::perm, Field::samples, UPPER_ONLY, and VERBOSE.
Referenced by mantelR().
{
    assert(X!=NULL);
    assert(Y!=NULL);
    assert(theCA!=NULL);
    assert(X->samples == Y->samples);
    //Compute correlation
    //initializeCA(theCA);
    float yVal;
    float xVal;
    int iPerm, jPerm;
    if(VERBOSE)
    {
        printf("Aggregating fields: \n");
        displayField(X);
        printf("AND\n");
        displayField(Y);
        printf("CA: N=%f, L=%f, R=%f\n", theCA->numerator,
               theCA->denominatorL, theCA->denominatorR);
    }
    for(int i=0; i<X->samples; i++)
    {
        if(VERBOSE) printf("\ti=%d\n",i);
        for(int j=0; j<X->samples; j++)
        {
            if(VERBOSE) printf("\t\tj=%d",j);
            //Caveat: Skip main diagonal
            if(i!=j)
            {
                iPerm = Y->perm->index[i];
                jPerm = Y->perm->index[j];
                yVal  = Y->element[iPerm][jPerm];
                iPerm = X->perm->index[i];
                jPerm = X->perm->index[j];
                xVal  = X->element[iPerm][jPerm];
                //2x efficiency: Only need upper triangle
                if(!(UPPER_ONLY && isInLowerDiagonal(i, j)))
                {
                    if(VERBOSE) printf("\t\t\tx=%f, y=%f, ", xVal, yVal);
                    augmentCAByValues(theCA, xVal, yVal);
                    if(VERBOSE) printf("n=%f, L=%f, R=%f", theCA->numerator,
                           theCA->denominatorL, theCA->denominatorR);
                }
            }
            if(VERBOSE) printf("\n");
        }
    }
}
void augmentCAByValues (CorrelationAggregate * theCA, float xmxbar, float ymybar)
Add data to a correlation aggregate.
Parameters:
theCA CorrelationAggregate to augment
xmxbar Value of x-xbar to use
ymybar Value of y-ybar to use
Side Effects:
Adds (x-xbar)*(y-ybar) to numerator, similar quantities to denominators.
Definition at line 478 of file functions.c.
References CorrelationAggregate::denominatorL, CorrelationAggregate::denominatorR, and CorrelationAggregate::numerator.
Referenced by augmentCAByFields(), testAugmentCAByValues(), and testFinishCorrelation().
{
    assert(theCA!=NULL);
    theCA->numerator += xmxbar*ymybar;
    theCA->denominatorL += xmxbar*xmxbar;
    theCA->denominatorR += ymybar*ymybar;
}
rankAndCount* computeRankInList (float datum, List * theData, rankAndCount * theRank)
Definition at line 922 of file functions.c.
References allocateRankAndCount(), rankAndCount::count, List::count, List::data, rankAndCount::indexEnd, rankAndCount::indexStart, inOrder(), List::isSorted, makeListFromList(), modifyListSortify(), and rankAndCount::rank.
Referenced by correlateAndFindP(), correlatePartialAndFindP(), modifyLandscapeRankify(), and testComputeRankInList().
{
    assert(theData!=NULL);
    bool noRank = (theRank == NULL);
    if(noRank) theRank = allocateRankAndCount();
    bool workingOnCopy = ! theData->isSorted;
    if(workingOnCopy)
    {
        printf("Note: Your data is being copied to sort.\n");
        theData = makeListFromList(theData);
        modifyListSortify(theData);
    }
    //Binary search for a match
    int iguess = (theData->count)/2; //Search index
    int ilo=0;  //Low index
    int ihi=theData->count; //High index
    float candidate = theData->data[iguess]; //Found data
    while(candidate != datum)
    {
        //DELETEME printf("Datum(%f)!=Candidate(%f). <%d | %d | %d>\n", datum, candidate, ilo, iguess, ihi);
        if(ihi<ilo)
        { //Candidate does not exist in list
            theRank->count = 0;
            theRank->rank = (ihi+ilo)/2.0;
            return theRank;
        }
        //DELETEME printf("DBEUG: Check this faster search work!\n");
        if(inOrder(candidate, datum)) ihi=iguess-1;
        else ilo=iguess+1;
        iguess = (ilo+ihi)/2;
        candidate = theData->data[iguess];
    }
    ilo=ihi=iguess; //Expand match to range
    while(theData->data[ilo]==datum && ilo>=0) ilo--; //find pre-firt-match
    while(theData->data[ihi]==datum && ihi<theData->count) ihi++; //find post-last-match
    //Construct answer
    theRank->count = ((ihi-1)-ilo); //Elements between low and high
    theRank->rank = (ilo+ihi)/2.0; //Average position btwn low and high
    theRank->indexEnd = ihi-1;
    theRank->indexStart = ilo+1;
    if(workingOnCopy){ free(theData); } //No memory leak!
    return theRank;
}
StatisticalData* correlateAndFindP (Landscape * lPermuted, Landscape * lPreserved, int trials)
Run input data through multiple correlations.
Parameters:
theFieldSet DataSet structure containing data to permute and correlate
trials Number of permutations to correlate
Returns:
StatisticalData on the rank of the first correlation among all the rest
Definition at line 602 of file functions.c.
References allocateArrayOfFloats(), allocateCA(), allocateList(), allocateStatData(), computeRankInList(), StatisticalData::correlationOfInterest, StatisticalData::correlationType, List::count, List::data, Landscape::fields, StatisticalData::listOfCorrelations, mantelR(), modifyLandscapeMeanify(), modifyListSortify(), modifyPermPermutify(), Landscape::numFields, Field::perm, StatisticalData::rankInfo, SEED_IDENTITY, and SEED_RANDOM.
Referenced by processFilePairs().
{
    assert(lPermuted!=NULL);
    assert(lPreserved!=NULL);
    assert(lPermuted->numFields == lPreserved->numFields);
    StatisticalData* theResults=allocateStatData();
    theResults->listOfCorrelations = allocateList();
    theResults->listOfCorrelations->count = trials;
    theResults->listOfCorrelations->data = allocateArrayOfFloats(trials);
    float currentCor;
    CorrelationAggregate* aCA = allocateCA();
    theResults->correlationType = "Unset";
    modifyLandscapeMeanify(lPreserved);
    modifyLandscapeMeanify(lPermuted);
    for(int perm=0; perm<trials; perm++)
    {
        //Make new random permutations
        for(int f=0; f<lPreserved->numFields; f++)
        {
            //Identity permutation the first time through, random the rest
            modifyPermPermutify(lPermuted->fields[f]->perm,
                                (!perm)?SEED_IDENTITY:SEED_RANDOM);
        }
        currentCor=mantelR(lPreserved, lPermuted, aCA);
        theResults->listOfCorrelations->data[perm] = currentCor;
        //Store the first result specially
        if(!perm) theResults->correlationOfInterest = currentCor;
    }
    modifyListSortify(theResults->listOfCorrelations);
    theResults->rankInfo = computeRankInList(theResults->correlationOfInterest,
                                             theResults->listOfCorrelations,
                                             NULL);
    return theResults;
}
StatisticalData* correlatePartialAndFindP (Landscape * lPermuted, Landscape * lPreserved, Landscape * lGiven, int trials)
Definition at line 643 of file functions.c.
References allocateArrayOfFloats(), allocateCA(), allocateList(), allocateStatData(), computeRankInList(), StatisticalData::correlationOfInterest, StatisticalData::correlationType, List::count, List::data, Landscape::fields, StatisticalData::listOfCorrelations, mantelRPartial(), modifyLandscapeMeanify(), modifyListSortify(), modifyPermPermutify(), Landscape::numFields, Field::perm, StatisticalData::rankInfo, SEED_IDENTITY, and SEED_RANDOM.
Referenced by processFileTriples().
{
    assert(lPermuted!=NULL);
    assert(lPreserved!=NULL);
    assert(lGiven!=NULL);
    assert(lPermuted->numFields == lPreserved->numFields);
    assert(lGiven->numFields == lPreserved->numFields);
    StatisticalData* theResults=allocateStatData();
    theResults->listOfCorrelations = allocateList();
    theResults->listOfCorrelations->count = trials;
    theResults->listOfCorrelations->data = allocateArrayOfFloats(trials);
    float currentCor;
    CorrelationAggregate* aCA = allocateCA();
    theResults->correlationType = "Unset";
    modifyLandscapeMeanify(lPreserved);
    modifyLandscapeMeanify(lPermuted);
    modifyLandscapeMeanify(lGiven);
    for(int perm=0; perm<trials; perm++)
    {
        //Make new random permutations
        for(int f=0; f<lPreserved->numFields; f++)
        {
            //Identity permutation the first time through, random the rest
            modifyPermPermutify(lPermuted->fields[f]->perm,
                                (!perm)?SEED_IDENTITY:SEED_RANDOM);
        }
        currentCor=mantelRPartial(lPermuted, lPreserved, lGiven, aCA);
        theResults->listOfCorrelations->data[perm] = currentCor;
        //Store the first result specially
        if(!perm) theResults->correlationOfInterest = currentCor;
    }
    modifyListSortify(theResults->listOfCorrelations);
    theResults->rankInfo = computeRankInList(theResults->correlationOfInterest,
                                             theResults->listOfCorrelations,
                                             NULL);
    return theResults;
}
void displayField (Field * theField)
Display field data on screen.
Parameters:
theField Field structure to dump to file
Side Effects:
Displays field indices and flattened index around data
Definition at line 263 of file functions.c.
References Field::element, Perm::index, Field::perm, and Field::samples.
Referenced by augmentCAByFields(), and testDisplayField().
{
    assert(theField!=NULL);
    int index=0;
    float currentElement;
    int iPerm, jPerm;
    for(int x=0; x<theField->samples; x++)
    {
        for(int y=0; y<theField->samples; y++)
        {
            iPerm = theField->perm->index[x];
            jPerm = theField->perm->index[y];
            if(x!=y)
            {
                currentElement = theField->element[iPerm][jPerm];
                printf("(%d,%d)%3.2f{%2d} ", iPerm, jPerm, currentElement, index);
                index++;
            } else {
                printf("(%d,%d)  ><     ", iPerm, jPerm);
            }
        }
        printf("\n");
    }
}
void displayList (List * theData)
Display a list on screen.
Parameters:
theData The list to display
Side Effects:
Outputs contents of a list to screen
Definition at line 813 of file functions.c.
References List::count, List::data, and DISPLAY_DIGITS.
Referenced by testDisplayList().
{
    assert(theData!=NULL);
    printf("List %p: [ ", theData);
    for(int i=0; i<theData->count; i++)
    {
        printf("%.*f ", DISPLAY_DIGITS, theData->data[i]);
    }
    printf("]\n");
}
float finishCorrelation (CorrelationAggregate * theCA)
Extract result from correlation aggregate.
Parameters:
theCA CorrelationAggregate compute correlation from
Returns:
numerator/sqrt(denomL*denomR)
Definition at line 486 of file functions.c.
References CorrelationAggregate::denominatorL, CorrelationAggregate::denominatorR, FLOATIFY, and CorrelationAggregate::numerator.
Referenced by mantelR(), and testFinishCorrelation().
{
    assert(theCA!=NULL);
    float n,l,r;
    n=theCA->numerator;
    l=theCA->denominatorL;
    r=theCA->denominatorR;
    return (FLOATIFY*n)/(sqrt(l*r));
}
void heapSortSiftDown (List * theData, int root, int bottom)
Utility function for sorting.
Parameters:
theData The list bubble
root Node index to bubble down from
bottom Node index of last entry
Side Effects:
theData will contain same elements, in sorted order
Definition at line 884 of file functions.c.
References List::data, inOrder(), List::isSorted, and swapF().
Referenced by modifyListSortify().
{
    assert(theData!=NULL);
    //This process disorders things
    theData->isSorted = false;
    int farChild = root * 2 + 1;
    int sibling;
    while(farChild <= bottom)
    {
        // Find the biggest child
        if(farChild < bottom)
        {
            sibling = farChild + 1;
            // Reversed for stability
            if(!inOrder(theData->data[farChild], theData->data[sibling]))
            {
                farChild = sibling;
            }
        }
        // If we have the correct ordering, we are done.
        if(inOrder(theData->data[root], theData->data[farChild])) return;
        // Swap
        swapF(&theData->data[root], &theData->data[farChild]);
        root=farChild;
        farChild = root * 2 + 1;
    }
}
void initializeCA (CorrelationAggregate * theCA)
Initialize a correlation aggregate.
Parameters:
theCA CorrelationAggregate to initialize
Side Effects:
Sets all partial sums to zero
Definition at line 470 of file functions.c.
References CorrelationAggregate::denominatorL, CorrelationAggregate::denominatorR, and CorrelationAggregate::numerator.
Referenced by mantelR(), testAugmentCAByValues(), testFinishCorrelation(), and testInitializeCA().
{
    assert(theCA!=NULL);
    theCA->numerator = 0;
    theCA->denominatorL = 0;
    theCA->denominatorR = 0;
}
bool inOrder (float l, float r)
Check if inputs are in desired order.
Parameters:
l Allegedly first element
r Allegedly second element
Returns:
TRUE when l<r, FALSE when r<l.
Definition at line 48 of file functions.c.
Referenced by computeRankInList(), heapSortSiftDown(), testInOrder(), and testModifyListSortify().
{
    return l >= r;
}
bool isInLowerDiagonal (int i, int j)
Definition at line 325 of file functions.c.
Referenced by augmentCAByFields(), and modifyLandscapeMeanify().
{ return i<j; }
Field* makeFieldFromTDV (const char * filename)
Load a tab-delimited-value file into a Field.
Parameters:
filename Filename for the TDV file.
Returns:
A Field with contents matching the TDV file.
Definition at line 175 of file functions.c.
References allocateArrayOfArraysOfFloats(), allocateArrayOfFloats(), allocateField(), Field::element, Field::fieldnum, Field::hasFlatVersion, makePerm(), Field::perm, Field::samples, and SEED_IDENTITY.
Referenced by makeLandscapeFromTDVs(), and testLoadAndSaveFieldTDV().
{
    assert(filename!=NULL);
    int fieldnum, samples, scan;
    FILE *theFile = fopen(filename, "r");
    assert(theFile); //Gotta have a file to process
    scan=fscanf(theFile, "<Field %d:Samples %d>",
                &fieldnum, &samples);
    if(scan!=2)
    {
        printf("ERROR: Bad input file <%s> missing header.\n", filename);
        fclose(theFile);
    } else {
        printf("Reading [%s] field=%d, samples=%d\n", filename, fieldnum, samples);
    }
    assert(scan==2);
    Field* theField = allocateField();
    theField->samples = samples;
    theField->fieldnum = fieldnum;
    theField->element = allocateArrayOfArraysOfFloats(samples);
    theField->hasFlatVersion = false;
    theField->perm = makePerm(samples, SEED_IDENTITY);
//    theField->isCentered = false;
//    theField->isRanked = false;
//    theField->isRankBased = false;
//    theField->isRaw = true;
    for(int x=0; x<samples; x++)
    {
        theField->element[x] = allocateArrayOfFloats(samples);
        for(int y=0; y<samples; y++)
        {
            fscanf(theFile, "%f", &theField->element[x][y]);
            //Funny message when main diagonal nonzero
            if(x==y && theField->element[x][y]!=0) printf("HEY! Nonzero on main diagonal.\n");
        }
    }
    fclose(theFile);
    return theField;
}
Landscape* makeLandscapeFromTDVs (int files, const char * filenames[])
Definition at line 296 of file functions.c.
References allocateArrayOfFields(), allocateLandscape(), Landscape::fields, Landscape::flatVersion, Landscape::hasFlatVersion, Landscape::isCentered, Landscape::isRankBased, Landscape::isRanked, Landscape::isRaw, makeFieldFromTDV(), Landscape::numFields, Landscape::numNonDiagElts, and Field::samples.
Referenced by processFilePairs(), and processFileTriples().
{
    assert(files>0);
    assert(filenames!=NULL);
    Landscape* theScape = NULL;
    theScape = allocateLandscape();
    theScape->numFields = files;
    theScape->fields = allocateArrayOfFields(files);
    theScape->numNonDiagElts=0;
    int n;
    for(int i=0; i<files; i++)
    {
        theScape->fields[i] = makeFieldFromTDV(filenames[i]);
        n=theScape->fields[i]->samples;
        theScape->numNonDiagElts  += n*n-n;
    }
    theScape->isRaw = true;
    theScape->isRanked=false;
    theScape->isRankBased=false;
    theScape->isCentered=false;
    theScape->hasFlatVersion=false;
    theScape->flatVersion=NULL;
    return theScape;
}
List* makeListFromLandscape (Landscape * theData)
Flatten a 2D field to a 1D list.
Parameters:
theField Field data to flatten
Returns:
A List containing all the elements of theField
Side Effects:
Adds flattened list to theField for memoization.
Definition at line 978 of file functions.c.
References allocateArrayOfFloats(), allocateList(), List::count, List::data, Field::element, Landscape::fields, Landscape::flatVersion, Landscape::hasFlatVersion, List::isMeanValid, List::isSorted, List::mean, Landscape::numFields, Landscape::numNonDiagElts, and Field::samples.
Referenced by modifyLandscapeRankify().
{
    assert(theData!=NULL);
    if(theData->hasFlatVersion) return theData->flatVersion;
    //Create a list of the appropriate size
    List* theList = allocateList();
    theList->count = theData->numNonDiagElts;
    theList->data = allocateArrayOfFloats(theList->count);
    theList->isSorted = false;
    //Fill list with data
    float currentElement;
    Field* theField;
    int index=0;
    float runningTotal=0.0;
    for(int f=0; f<theData->numFields; f++)
    {
        theField = theData->fields[f];
        for(int x=0; x<theField->samples; x++)
        {
            for(int y=0; y<theField->samples; y++)
            {
                //Caveat: Skip main diagonal
                if(x!=y)
                {
                    index++;
                    currentElement = theField->element[x][y];
                    theList->data[index] = currentElement;
                    runningTotal += currentElement;
                }
            }
        }
    }
    //May as well have the mean on hand, just in case.
    theList->mean = runningTotal / index;
    theList->isMeanValid = true;
    //Store list for later re-use
    theData->hasFlatVersion = true;
    theData->flatVersion = theList;
    return theList;
}
List* makeListFromList (List * theData)
Create a List by copying another list.
Parameters:
theData List to copy
Returns:
a copy of theData
Definition at line 797 of file functions.c.
References allocateArrayOfFloats(), allocateList(), List::count, List::data, List::isMeanValid, List::isSorted, and List::mean.
Referenced by computeRankInList(), and testMakeListFromList().
{
    assert(theData!=NULL);
    List* theCopy = allocateList();
    theCopy->isSorted = theData->isSorted;
    theCopy->mean = theData->mean;
    theCopy->isMeanValid = theData->isMeanValid;
    theCopy->count = theData->count;
    theCopy->data = allocateArrayOfFloats(theCopy->count);
    for(int i=0; i<theCopy->count; i++)
    {
        theCopy->data[i] = theData->data[i];
    }
    return theCopy;
}
Perm* makePerm (int size, int seed)
Creates a permutation of a given size.
Parameters:
size How many elements to permute
seed 0 for identity permutation, -1 for existing randomization, >0 for a known seed value
Returns:
a random permutation unless seed is 0
Definition at line 84 of file functions.c.
References allocateArrayOfInts(), allocatePermutation(), Perm::index, randInRange(), and Perm::size.
Referenced by makeFieldFromTDV(), makeRandomField(), testMakePerm(), and testModifyPermPermutify().
{
    assert(size>0);
    if(seed>0) srand(seed);
    Perm* thePerm = allocatePermutation();
    thePerm->size = size;
    thePerm->index = allocateArrayOfInts(size);
    int j;
    thePerm->index[0] = 0;
    for(int i=1; i<size; i++)
    {
        if(!seed)
        {
            thePerm->index[i] = i;
        } else {
            j = randInRange(0, i);
            thePerm->index[i] = thePerm->index[j];
            thePerm->index[j] = i;
        }
    }
    return thePerm;
}
Field* makeRandomField (int samples)
Create a symmetric Field with random data.
Parameters:
samples Width (and height) of the comparison matrix
Returns:
a randomly generated Field (symmetric, zero on diagonal)
Definition at line 140 of file functions.c.
References allocateArrayOfArraysOfFloats(), allocateArrayOfFloats(), allocateField(), Field::element, Field::fieldnum, Field::hasFlatVersion, makePerm(), Field::perm, randInRange(), Field::samples, and SEED_IDENTITY.
Referenced by makeTestFiles(), testDisplayField(), testLoadAndSaveFieldTDV(), and testMakeRandomField().
{
    assert(samples>0);
    Field* theField = allocateField();
    theField->samples = samples;
    theField->fieldnum = randInRange(90, 99);
    theField->element = allocateArrayOfArraysOfFloats(samples);
    theField->hasFlatVersion = false;
    theField->perm = makePerm(samples, SEED_IDENTITY);
//    theField->isCentered = false;
//    theField->isRanked = false;
//    theField->isRankBased = false;
//    theField->isRaw = true;
    for(int x=0; x<samples; x++)
    {
        theField->element[x] = allocateArrayOfFloats(samples);
    }
    for(int x=0; x<samples; x++)
    {
        for(int y=x; y<samples; y++)
        {
            if(x==y) theField->element[x][y] = 0;
            else
            {
                //theField->element[x][y] = randInRange(0, 99)/10.0;
                theField->element[x][y] = randInRange(0, 9)/1.0;
                theField->element[y][x] = theField->element[x][y];
            }
        }
    }
    return theField;
}
float mantelR (Landscape * mPreserved, Landscape * mPermuted, CorrelationAggregate * theCA)
Find correlation of two sets of fields.
Parameters:
theFieldSet DataSet containing base fields and permutation to use
theCA optional (NULL for auto) correlation aggregator
Returns:
correlation value between base fields
Definition at line 552 of file functions.c.
References allocateCA(), augmentCAByFields(), Landscape::fields, finishCorrelation(), initializeCA(), Landscape::isCentered, and Landscape::numFields.
Referenced by correlateAndFindP(), and mantelRPartial().
{
    assert(mPermuted!=NULL);
    assert(mPreserved!=NULL);
    assert(mPermuted->numFields==mPreserved->numFields);
    assert(mPreserved->isCentered);
    assert(mPermuted->isCentered);
    //If no aggregator supplied, create a temporary one.
    bool noAggregator = (theCA == NULL);
    if(noAggregator) theCA = allocateCA();
    //Compute partial sums
    initializeCA(theCA);
    for(int f=0; f<mPermuted->numFields; f++)
    {
        augmentCAByFields(theCA, mPreserved->fields[f], mPermuted->fields[f]);
    }
    //Process aggregated correlator
    float theCorrelation = finishCorrelation(theCA);
    if(noAggregator) free(theCA);
    return theCorrelation;
}
float mantelRPartial (Landscape * mPermuted, Landscape * mPreserved, Landscape * mGiven, CorrelationAggregate * theCA)
Definition at line 579 of file functions.c.
References allocateCA(), and mantelR().
Referenced by correlatePartialAndFindP().
{
    //If no aggregator supplied, create a temporary one.
    bool noAggregator = (theCA == NULL);
    if(noAggregator) theCA = allocateCA();
    float AB = mantelR(mPreserved, mPermuted, theCA);
    float AC = mantelR(mGiven,     mPermuted, theCA);
    float BC = mantelR(mPreserved, mGiven,    theCA);
    if(noAggregator) free(theCA);
    return (AB-AC*BC)/sqrt((1-AC*AC)*(1-BC*BC));
}
void modifyLandscapeMeanify (Landscape * theData)
Definition at line 327 of file functions.c.
References Field::element, Landscape::fields, Landscape::flatVersion, Landscape::hasFlatVersion, Landscape::isCentered, isInLowerDiagonal(), Landscape::isRankBased, Landscape::isRanked, Landscape::isRaw, Landscape::numFields, Field::samples, and UPPER_ONLY.
Referenced by correlateAndFindP(), and correlatePartialAndFindP().
{
    assert(theData!=NULL);
    float theTotal = 0.0;
    int theCount=0;
    //Has this already been done?
    if(theData->isCentered) return;
    //Processed data isn't raw
    theData->isRaw=false;
    //Is this formerly-ranked data?
    if(theData->isRanked)
    {
        theData->isRankBased=true;
    } else {
        theData->isRankBased=false;
    }
    //Either way, it's not ranked anymore.
    theData->isRanked=false;
    //old flat version now invalid. Clear out the memory it used.
    theData->hasFlatVersion=false;
    if(theData->flatVersion != NULL)
    {
        free(theData->flatVersion);
        theData->flatVersion=NULL;
    }
    int currentSampleSize;
    //Step one: Find mean
    for(int f=0; f<theData->numFields; f++)
    {
        currentSampleSize = theData->fields[f]->samples;
        for(int x=0; x<currentSampleSize; x++)
        {
            for(int y=0; y<currentSampleSize; y++)
            {
                //Caveat: Skip main diagonal
                if(x!=y)
                {
                    //2x efficiency: Only need upper triangle
                    if(!(UPPER_ONLY && isInLowerDiagonal(x,y)))
                    {
                        theTotal += theData->fields[f]->element[x][y];
                        theCount++;
                    }
                }
            }
        }
    }
    float theMean = theTotal / theCount;
    //Step two: subtract off the mean
    for(int f=0; f<theData->numFields; f++)
    {
        currentSampleSize = theData->fields[f]->samples;
        for(int x=0; x<currentSampleSize; x++)
        {
            for(int y=0; y<currentSampleSize; y++)
            {
                //Caveat: Skip main diagonal and one redundant triangle
                if(x!=y && x>y)
                {
                    theData->fields[f]->element[x][y] -= theMean;
                    theData->fields[f]->element[y][x] -= theMean;
                }
            }
        }
    }
    //It's now centered!
    theData->isCentered=true;
}
void modifyLandscapeRankify (Landscape * theData)
Definition at line 409 of file functions.c.
References computeRankInList(), Field::element, Landscape::fields, Landscape::flatVersion, Landscape::hasFlatVersion, Landscape::isCentered, Landscape::isRankBased, Landscape::isRanked, Landscape::isRaw, makeListFromLandscape(), modifyListSortify(), Landscape::numFields, rankAndCount::rank, and Field::samples.
Referenced by processFilePairs(), and processFileTriples().
{
    assert(theData!=NULL);
    //Make sure this isn't redundant effort
    if(theData->isRanked) return;
    //Processed data isn't raw
    theData->isRaw=false;
    //Ranking uncenters data
    theData->isCentered=false;
    List* sorted = makeListFromLandscape(theData);
    modifyListSortify(sorted);
    //Old flat version is unranked and out of order, so nix it
    theData->hasFlatVersion=false;
    theData->flatVersion=NULL;
    rankAndCount* rankInfo = NULL;
    int currentSampleSize;
    for(int f=0; f<theData->numFields; f++)
    {
        currentSampleSize = theData->fields[f]->samples;
        for(int x=0; x<currentSampleSize; x++)
        {
            for(int y=0; y<currentSampleSize; y++)
            {
                //Caveat: Skip main diagonal and one (redundant) triangle
                if(x!=y && x>y)
                {
                    rankInfo = computeRankInList(theData->fields[f]->element[x][y],
                                                 sorted, rankInfo);
                    theData->fields[f]->element[x][y] = rankInfo->rank;
                    theData->fields[f]->element[y][x] = rankInfo->rank;
                }
            }
        }
    }
    free(rankInfo);
    //sorted list should no longer be in use by anyone
    free(sorted);
    //We're now ranked!
    theData->isRanked=true;
    //Ranked data is also rank-based
    theData->isRankBased=true;
}
void modifyListMeanify (List * theData)
Center a list about its mean.
Parameters:
theData The list to center
Side Effects:
Set all elements X of theData to X-Xbar, where Xbar is mean of elements in theData
Definition at line 836 of file functions.c.
References List::count, List::data, List::isMeanValid, and List::mean.
Referenced by testModifyListMeanify().
{
    assert(theData!=NULL);
    float theTotal = 0.0;
    int theCount=0;
    if(!theData->isMeanValid)
    {
        for(int i=0; i<theData->count; i++)
        {
            theTotal += theData->data[i];
            theCount++;
        }
        theData->mean = theTotal / theCount;
        theData->isMeanValid = true;
    }
    for(int i=0; i<theData->count; i++)
    {
        theData->data[i] -= theData->mean;
    }
    theData->mean = 0.0;
}
void modifyListSortify (List * theData)
Sort a list (heapsort)
Parameters:
theData The list to sort
Side Effects:
theData will contain same elements, in sorted order
Definition at line 866 of file functions.c.
References List::count, List::data, heapSortSiftDown(), List::isSorted, and swapF().
Referenced by computeRankInList(), correlateAndFindP(), correlatePartialAndFindP(), modifyLandscapeRankify(), testComputeRankInList(), and testModifyListSortify().
{
    assert(theData!=NULL);
    if(theData->isSorted) return; //Why bother? It's sorted already
    for (int i = (theData->count / 2); i >= 0; i--)
        heapSortSiftDown(theData, i, theData->count-1);
    for (int i = theData->count-1; i >= 1; i--)
    {
        swapF(&theData->data[0], &theData->data[i]);
        heapSortSiftDown(theData, 0, i-1);
    }
    theData->isSorted = true; //Flag result for future timesaving
}
void modifyPermPermutify (Perm * thePerm, int seed)
Change a permutation.
Parameters:
thePerm Permutation to permute
seed 0 for identity permutation, -1 for existing randomization, >0 for a known seed value
Side Effects:
Permutes thePerm
Definition at line 111 of file functions.c.
References Perm::index, randInRange(), Perm::size, and swapI().
Referenced by correlateAndFindP(), correlatePartialAndFindP(), and testModifyPermPermutify().
{
    assert(thePerm!=NULL);
    if(seed>0) srand(seed);
    int j;
    //Including 0 because the last swap hurts nobody,
    //and with no seed the last step finishes setting the
    //permutation to the identity
    for(int i=thePerm->size-1; i>=0; i--)
    {
        if(!seed)
        {
            thePerm->index[i] = i;
        } else {
            j = randInRange(0, i);
            swapI(&thePerm->index[i], &thePerm->index[j]);
        }
    }
}
void processFilePairs (int trials, int filesets, const char * argv[], int timestamp)
Creates files containing data on Spearman and Person correlation of inputs.
Parameters:
trials Number of permutations to correlate for each type
filepairs Number of substrata that will be supplied
argv Array of (original) command-line arguments.
timestamp Time used for random seed, and to put in filenames
Side Effects:
Creates testinfo.TIMESTAMP.[Pearson|Spearman].[txt|tdv] files.
Definition at line 720 of file functions.c.
References correlateAndFindP(), StatisticalData::correlationType, makeLandscapeFromTDVs(), modifyLandscapeRankify(), and saveData().
Referenced by main().
{
    const char* s[filesets]; //static: distances
    const char* p[filesets]; //permuted: differences
    int groupSize=2;
    int firstFile=2;
    for(int i=0; i<filesets; i++)
    {
        s[i] = argv[groupSize*i+firstFile];
        p[i] = argv[groupSize*i+firstFile+1];
    }
    //Load data
    Landscape* lPreserved = makeLandscapeFromTDVs(filesets, s);
    Landscape* lPermuted = makeLandscapeFromTDVs(filesets, p);
    StatisticalData* theStats = NULL;
    //Pearson correlation
    theStats = correlateAndFindP(lPermuted, lPreserved, trials);
    theStats->correlationType = "Pearson";
    saveData(theStats, timestamp);
    //Rank data
    modifyLandscapeRankify(lPreserved);
    modifyLandscapeRankify(lPermuted);
    //Spearman correlation
    theStats = correlateAndFindP(lPermuted, lPreserved, trials);
    theStats->correlationType = "Spearman";
    saveData(theStats, timestamp);
}
void processFileTriples (int trials, int filesets, const char * argv[], int timestamp)
Definition at line 753 of file functions.c.
References correlatePartialAndFindP(), StatisticalData::correlationType, makeLandscapeFromTDVs(), modifyLandscapeRankify(), and saveData().
{
    const char* s[filesets]; //static: distances
    const char* p[filesets]; //permuted: differences
    const char* g[filesets]; //given: differences to relativize by
    int groupSize = 3;
    int firstFile = 2;
    for(int i=0; i<filesets; i++)
    {
        s[i] = argv[groupSize*i+firstFile];
        p[i] = argv[groupSize*i+firstFile+1];
        g[i] = argv[groupSize*i+firstFile+2];
    }
    //Load data
    Landscape* lPreserved = makeLandscapeFromTDVs(filesets, s);
    Landscape* lPermuted = makeLandscapeFromTDVs(filesets, p);
    Landscape* lGiven = makeLandscapeFromTDVs(filesets, g);
    StatisticalData* theStats = NULL;
    //Pearson correlation
    theStats = correlatePartialAndFindP(lPermuted, lPreserved, lGiven, trials);
    theStats->correlationType = "Pearson (Partial)";
    saveData(theStats, timestamp);
    //Rank data
    modifyLandscapeRankify(lPreserved);
    modifyLandscapeRankify(lPermuted);
    modifyLandscapeRankify(lGiven);
    //Spearman correlation
    theStats = correlatePartialAndFindP(lPermuted, lPreserved, lGiven, trials);
    theStats->correlationType = "Spearman (Partial)";
    saveData(theStats, timestamp);
}
int randInRange (int lo, int hi)
Generate random number in a given range.
Parameters:
lo Smallest number allowable for output
hi Largest number allowable for output
Returns:
integer n, lo<=n<=hi
Definition at line 39 of file functions.c.
Referenced by makePerm(), makeRandomField(), makeTestList(), modifyPermPermutify(), and testRandInRange().
{
    assert(lo<=hi);
    int range = hi-lo+1;
    int num = rand()%range;
    num = num + lo;
    return num;
}
void saveData (StatisticalData * dataToSave, int timestamp)
Saves statistical data to file.
Parameters:
timestamp Identifier to distinguish files from different runs
dataToSave Statistical data to output to file
Side Effects:
Creates a .txt and a .tdv file containing summary info and data for a histogram.
Definition at line 691 of file functions.c.
References StatisticalData::correlationOfInterest, StatisticalData::correlationType, rankAndCount::count, List::count, FLOATIFY, StatisticalData::listOfCorrelations, rankAndCount::rank, StatisticalData::rankInfo, and saveListToTDV().
Referenced by processFilePairs(), and processFileTriples().
{
    assert(dataToSave!=NULL);
    FILE* output = NULL;
    char fname[100];
    int trials = dataToSave->listOfCorrelations->count;
    float rank = dataToSave->rankInfo->rank+1;
    sprintf(fname, "testinfo.%d.%s.%s",
            timestamp, dataToSave->correlationType, "txt");
    output = fopen(fname, "w");
    fprintf(output, "%s correlation is %f\n",
            dataToSave->correlationType,
            dataToSave->correlationOfInterest);
    fprintf(output, "In %d trials, %d matches had average rank %f\n",
            trials, dataToSave->rankInfo->count, rank);
    fprintf(output, "Assuming uniqueness, %f of the trials were >=\n",
            (trials - rank)/(FLOATIFY*trials));
    fprintf(output, "Assuming uniqueness, %f of the trials were <=\n",
            (rank)/(FLOATIFY*trials));
    fclose(output);
    sprintf(fname, "testinfo.%d.%s.%s",
            timestamp, dataToSave->correlationType, "tdv");
    saveListToTDV(fname, dataToSave->listOfCorrelations);
}
void saveFieldToHTML (const char * filename, Field * theField)
Save field data to file.
Parameters:
filename Name of file to create/overwrite with data
theField Field structure to dump to file
Side Effects:
creates/overwrites an HTML Table file
Definition at line 240 of file functions.c.
References Field::element, Perm::index, Field::perm, and Field::samples.
{
    assert(filename!=NULL);
    assert(theField!=NULL);
    FILE* theFile = fopen(filename, "w");
    fprintf(theFile, "<table>\n");
    int iPerm, jPerm;
    for(int i=0; i<theField->samples; i++)
    {
        fprintf(theFile, "<tr>");
        for(int j=0; j<theField->samples; j++)
        {
            iPerm = theField->perm->index[i];
            jPerm = theField->perm->index[j];
            fprintf(theFile, "<td>%f</td>", theField->element[iPerm][jPerm]);
        }
        fprintf(theFile, "</tr>\n");
    }
    fprintf(theFile, "</table>");
    fclose(theFile);
}
void saveFieldToTDV (const char * filename, Field * theField)
Save field data to file.
Parameters:
filename Name of file to create/overwrite with data
theField Field structure to dump to file
Side Effects:
creates/overwrites tab-delimited file
Definition at line 218 of file functions.c.
References Field::element, Field::fieldnum, Perm::index, Field::perm, and Field::samples.
Referenced by makeTestFiles(), testDisplayField(), and testLoadAndSaveFieldTDV().
{
    assert(filename!=NULL);
    assert(theField!=NULL);
    FILE* theFile = fopen(filename, "w");
    fprintf(theFile, "<Field %d:Samples %d>\n", theField->fieldnum, theField->samples);
    int iPerm, jPerm;
    for(int i=0; i<theField->samples; i++)
    {
        for(int j=0; j<theField->samples; j++)
        {
            iPerm = theField->perm->index[i];
            jPerm = theField->perm->index[j];
            fprintf(theFile, "%f", theField->element[iPerm][jPerm]);
            if(j<theField->samples-1) fprintf(theFile, "\t");
        }
        fprintf(theFile, "\n");
    }
    fclose(theFile);
}
void saveListToTDV (const char * filename, List * theData)
Output a list to file.
Parameters:
filename Name of file to store data in
theData The list to output
Side Effects:
Create/overwrite
Definition at line 824 of file functions.c.
References List::count, and List::data.
Referenced by saveData(), and testSaveListToTDV().
{
    assert(theData!=NULL);
    FILE* fout = fopen(filename, "w");
    assert(fout!=NULL);
    for(int i=0; i<theData->count; i++)
    {
        fprintf(fout, "%f\t", theData->data[i]);
    }
    fclose(fout);
}
void swapF (float * l, float * r)
Exchange contents of two float variables.
Parameters:
l A variable to swap
r A variable to swap
Side Effects:
Exchanges contents of l and r
Definition at line 52 of file functions.c.
Referenced by heapSortSiftDown(), modifyListSortify(), and testSwapF().
{
    assert(l!=NULL);
    assert(r!=NULL);
    float temp;
    temp = *l;
    *l = *r;
    *r = temp;
}
void swapI (int * l, int * r)
Exchange contents of two int variables.
Parameters:
l A variable to swap
r A variable to swap
Side Effects:
Exchanges contents of l and r
Definition at line 62 of file functions.c.
Referenced by modifyPermPermutify(), and testSwapI().
{
    assert(l!=NULL);
    assert(r!=NULL);
    int temp;
    temp = *l;
    *l = *r;
    *r = temp;
}