Pearson and Spearman correlation with restricted permutation: SP_Correlation/SP_Correlation/tests.c File Reference
SP_Correlation/SP_Correlation/tests.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <time.h>
#include <math.h>
#include "tests.h"
#include "functions.h"
Defines
#define TEST_SEED 31415
Functions
void makeTestFiles (void)
Create a number of data files to test correlation with.
bool runTests (void)
Test functions for correct behavior.
void reportStart (char *function)
bool reportEnd (bool good, char *explanation)
bool reportFake (void)
bool testRandInRange (void)
Generate random number in a given range.
bool testInOrder (void)
Check if inputs are in desired order.
bool testSwapF (void)
Exchange contents of two float variables.
bool testSwapI (void)
Exchange contents of two int variables.
bool testInitializeCA (void)
Initialize a correlation aggregate.
bool testAugmentCAByValues (void)
Add data to a correlation aggregate.
bool testFinishCorrelation (void)
Extract result from correlation aggregate.
bool testMakePerm (void)
Creates a permutation of a given size.
void showPermutation (Perm *thePerm)
bool testModifyPermPermutify (void)
Change a permutation.
List * makeTestList (void)
bool testMakeListFromList (void)
Create a List by copying another list.
bool testDisplayList (void)
Display a list on screen.
bool testSaveListToTDV (void)
Output a list to file.
bool testModifyListMeanify (void)
Center a list about its mean.
bool testModifyListSortify (void)
Sort a list (heapsort)
bool testComputeRankInList (void)
bool testMakeRandomField (void)
Create a symmetric Field with random data.
bool testLoadAndSaveFieldTDV (void)
bool testMakeFieldFromTDV (void)
Load a tab-delimited-value file into a Field.
bool testSaveFieldToTDV (void)
Save field data to file.
bool testDisplayField (void)
Display field data on screen.
bool testAugmentCAByFields (void)
Augment a correlation aggregate with information from two fields.
bool testMakeLandscapeFromTDVs (void)
bool testModifyLandscapeMeanify (void)
bool testModifyLandscapeRankify (void)
bool testMakeListFromField (void)
Flatten a 2D field to a 1D list.
bool testMakeListFromLandscape (void)
bool testMantelR (void)
Find correlation of two sets of fields.
bool testMantelRPartial (void)
bool testCorrelateAndFindP (void)
Run input data through multiple correlations.
bool testCorrelatePartialAndFindP (void)
bool testProcessFilePairs (void)
Creates files containing data on Spearman and Person correlation of inputs.
bool testProcessFileTriples (void)
Detailed Description
Author:
Bryant Adams
Date:
3/20/12
Definition in file tests.c.
Define Documentation
#define TEST_SEED 31415
Definition at line 18 of file tests.c.
Referenced by testMakePerm(), and testModifyPermPermutify().
Function Documentation
void makeTestFiles (void)
Create a number of data files to test correlation with.
Side Effects:
Creates Test1a.tdv, Test1b.tdv, Test2a.tdv, etc
Definition at line 19 of file tests.c.
References makeRandomField(), and saveFieldToTDV().
Referenced by runTests().
{
    Field* tmp;
    char filename[20];
    int size;
    for(int fieldNum=1; fieldNum<4; fieldNum++)
    {
        size = 1+fieldNum;
        for(int a=1; a<=2; a++)
        {
            tmp = makeRandomField(size);
            sprintf(filename, "Test%d%c.tdv", fieldNum, (a==1?'L':'R'));
            saveFieldToTDV(filename, tmp);
            free(tmp);
            tmp=NULL;
        }
    }
}
List * makeTestList (void)
Definition at line 315 of file tests.c.
References allocateArrayOfFloats(), allocateList(), List::count, List::data, List::isMeanValid, List::isSorted, and randInRange().
Referenced by testComputeRankInList(), testDisplayList(), testMakeListFromList(), testModifyListMeanify(), testModifyListSortify(), and testSaveListToTDV().
{
    List* theList = allocateList();
    int testEntries = 12;
    theList->count = testEntries;
    theList->data = allocateArrayOfFloats(testEntries);
    for(int i=0; i<testEntries; i++)
    {
        theList->data[i] = (randInRange(1, 99)/10.0);
    }
    theList->isMeanValid = false;
    theList->isSorted = false;
    return theList;
}
bool reportEnd (bool good, char * explanation)
Definition at line 113 of file tests.c.
Referenced by runTests(), testAugmentCAByFields(), testAugmentCAByValues(), testComputeRankInList(), testCorrelateAndFindP(), testCorrelatePartialAndFindP(), testDisplayField(), testDisplayList(), testFinishCorrelation(), testInitializeCA(), testInOrder(), testLoadAndSaveFieldTDV(), testMakeLandscapeFromTDVs(), testMakeListFromField(), testMakeListFromLandscape(), testMakeListFromList(), testMakePerm(), testMakeRandomField(), testMantelR(), testMantelRPartial(), testModifyLandscapeMeanify(), testModifyLandscapeRankify(), testModifyListMeanify(), testModifyListSortify(), testModifyPermPermutify(), testProcessFilePairs(), testProcessFileTriples(), testRandInRange(), testSaveListToTDV(), testSwapF(), and testSwapI().
{
    if(good)
    {
        printf("OK\n");
    } else {
        printf("BAD(%s)\n", explanation);
    }
    return good;
}
bool reportFake (void)
Definition at line 123 of file tests.c.
Referenced by testAugmentCAByFields(), testCorrelateAndFindP(), testCorrelatePartialAndFindP(), testMakeLandscapeFromTDVs(), testMakeListFromField(), testMakeListFromLandscape(), testMantelR(), testMantelRPartial(), testModifyLandscapeMeanify(), testModifyLandscapeRankify(), testProcessFilePairs(), and testProcessFileTriples().
{
    printf("Temporarily acceptible\n");
    return true;
}
void reportStart (char * function)
Definition at line 109 of file tests.c.
Referenced by testAugmentCAByFields(), testAugmentCAByValues(), testComputeRankInList(), testCorrelateAndFindP(), testCorrelatePartialAndFindP(), testDisplayField(), testDisplayList(), testFinishCorrelation(), testInitializeCA(), testInOrder(), testMakeFieldFromTDV(), testMakeLandscapeFromTDVs(), testMakeListFromField(), testMakeListFromLandscape(), testMakeListFromList(), testMakePerm(), testMakeRandomField(), testMantelR(), testMantelRPartial(), testModifyLandscapeMeanify(), testModifyLandscapeRankify(), testModifyListMeanify(), testModifyListSortify(), testModifyPermPermutify(), testProcessFilePairs(), testProcessFileTriples(), testRandInRange(), testSaveFieldToTDV(), testSaveListToTDV(), testSwapF(), and testSwapI().
{
    printf("Testing %s: ", function);
}
bool runTests (void)
Test functions for correct behavior.
Definition at line 38 of file tests.c.
References makeTestFiles(), reportEnd(), testAugmentCAByFields(), testAugmentCAByValues(), testComputeRankInList(), testCorrelateAndFindP(), testCorrelatePartialAndFindP(), testFinishCorrelation(), testInitializeCA(), testInOrder(), testMakeFieldFromTDV(), testMakeLandscapeFromTDVs(), testMakeListFromField(), testMakeListFromLandscape(), testMakeListFromList(), testMakePerm(), testMakeRandomField(), testMantelR(), testMantelRPartial(), testModifyLandscapeMeanify(), testModifyLandscapeRankify(), testModifyListMeanify(), testModifyListSortify(), testModifyPermPermutify(), testProcessFilePairs(), testProcessFileTriples(), testRandInRange(), testSaveFieldToTDV(), testSwapF(), and testSwapI().
{
    printf("Runtests still stubbed\n");
    void makeTestFiles();
    assert(testRandInRange());
    assert(testInOrder());
    assert(testSwapF());
    assert(testSwapI());
    assert(testInitializeCA());
    assert(testAugmentCAByValues());
    assert(testFinishCorrelation());
    assert(testMakePerm());
    assert(testModifyPermPermutify());
    assert(testMakeListFromList());
    //    assert( testDisplayList());
//    assert(testSaveListToTDV());
    assert( testModifyListMeanify());
    assert( testModifyListSortify());
    assert(testComputeRankInList());
    assert(testMakeRandomField());
    assert(testMakeFieldFromTDV());
    assert( testSaveFieldToTDV());
//    assert(testDisplayField());
#warning tests unimplemented
    assert(testAugmentCAByFields());
    assert(testMakeLandscapeFromTDVs());
    assert(testModifyLandscapeMeanify());
    assert(testModifyLandscapeRankify());
    assert(testMakeListFromField());
    assert(testMakeListFromLandscape());
    assert(testMantelR());
    assert(testMantelRPartial());
    assert(testCorrelateAndFindP());
    assert(testCorrelatePartialAndFindP());
    assert(testProcessFilePairs());
    assert(testProcessFileTriples());
    return reportEnd(true, NULL);
}
void showPermutation (Perm * thePerm)
Definition at line 271 of file tests.c.
References Perm::index, and Perm::size.
{
    printf("<Perm>[ ");
    for(int i=0; i<thePerm->size; i++)
    {
        printf("%d->%d ",i, thePerm->index[i]);
    }
    printf("]\n");
}
bool testAugmentCAByFields (void)
Augment a correlation aggregate with information from two fields.
Parameters:
X First field to correlate
Y Second field to correlate
theCA Correlation aggregate to store cumulative information
Returns:
the correlation so far, which may not be the final result
Side Effects:
Adds correlation information from fields X and Permute(Y) to theCA
Definition at line 557 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//CorrelationAggregate* theCA, Field* X, Field* Y
    reportStart("augmentCAByFields");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testAugmentCAByValues (void)
Add data to a correlation aggregate.
Definition at line 196 of file tests.c.
References allocateCA(), augmentCAByValues(), CorrelationAggregate::denominatorL, CorrelationAggregate::denominatorR, initializeCA(), CorrelationAggregate::numerator, reportEnd(), reportStart(), and testInitializeCA().
Referenced by runTests(), and testFinishCorrelation().
{
    assert(testInitializeCA());
    reportStart("augmentCAByValues");
    CorrelationAggregate* theCA = allocateCA();
    initializeCA(theCA);
    float xmxb = 3.0;
    float ymyb = 5.0;
    augmentCAByValues(theCA, xmxb, ymyb);
    if(theCA->numerator != xmxb*ymyb) return reportEnd(false, "numerator miscalc");
    if(theCA->denominatorL != xmxb*xmxb) return reportEnd(false, "X denominator miscalc");
    if(theCA->denominatorR != ymyb*ymyb) return reportEnd(false, "Y denominator miscalc");
    return reportEnd(true, NULL);
}
bool testComputeRankInList (void)
Definition at line 430 of file tests.c.
References computeRankInList(), rankAndCount::count, List::count, List::data, rankAndCount::indexEnd, rankAndCount::indexStart, makeTestList(), modifyListSortify(), rankAndCount::rank, reportEnd(), and reportStart().
Referenced by runTests().
{   reportStart("computeRankInList");
    float datum;
    List* theData;
    rankAndCount* theRank;
    theData = makeTestList();
    datum = theData->data[theData->count / 2];
    theRank = computeRankInList(datum, theData, NULL);
    modifyListSortify(theData);
//    displayList(theData);
    if(theData->data[(int)theRank->rank] != datum)
        return reportEnd(false, "incorrect rank");
    int countCheck = 0;
    for(int i=0; i<theData->count; i++)
    {
        if(theData->data[i] == datum)
        {
        countCheck++;
            if(i < theRank->indexStart)
                reportEnd(false, "bad start");
            if(i > theRank->indexEnd)
                reportEnd(false, "bad end");
        } else {
            if(theRank->indexStart < i && i < theRank->indexEnd)
                reportEnd(false, "nondatum in range");
        }
    }
    if(countCheck!=theRank->count) return reportEnd(false, "incorrect count");
    return reportEnd(true, NULL);
}
bool testCorrelateAndFindP (void)
Run input data through multiple correlations.
Parameters:
theFieldSet DataSet structure containing data to permute and correlate
trials Number of permutations to correlate
Returns:
StatisticalData on the rank of the first correlation among all the rest
Definition at line 655 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* lPermuted,     Landscape* lPreserved,     int trials
    reportStart("correlateAndFindP");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testCorrelatePartialAndFindP (void)
Definition at line 664 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* lPermuted,     Landscape* lPreserved,     Landscape* lGiven,     int trials
    reportStart("correlatePartialAndFindP");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testDisplayField (void)
Display field data on screen.
Definition at line 529 of file tests.c.
References displayField(), makeRandomField(), reportEnd(), reportStart(), and saveFieldToTDV().
{
    reportStart("displayField");
    Field* td = makeRandomField(8);
    saveFieldToTDV("displayTest.txt", td);
    printf("\n");
    displayField(td);
    printf("USER: Does the displayed field match the contents of displayText.txt?");
    char answer='w';
    while(answer!='Y' && answer!='N')
    {
        printf(" Y/N: ");
        scanf(" %c", &answer);
    }
    return reportEnd(answer=='Y', "User rejected");
}
bool testDisplayList (void)
Display a list on screen.
Definition at line 355 of file tests.c.
References displayList(), makeTestList(), reportEnd(), and reportStart().
{
    reportStart("displayList");
    displayList(makeTestList());
    printf("USER: did you just see a list?");
    char answer='w';
    while(answer!='Y' && answer!='N')
    {
        printf(" Y/N: ");
        scanf(" %c", &answer);
    }
    return reportEnd(answer=='Y', "User rejected");
}
bool testFinishCorrelation (void)
Extract result from correlation aggregate.
Definition at line 214 of file tests.c.
References allocateCA(), augmentCAByValues(), finishCorrelation(), initializeCA(), reportEnd(), reportStart(), testAugmentCAByValues(), and testInitializeCA().
Referenced by runTests().
{
    assert(testInitializeCA());
    assert(testAugmentCAByValues());
    reportStart("finishCorrelation");
    CorrelationAggregate* theCA = allocateCA();
    initializeCA(theCA);
    float x1=3.0;
    float y1=4.0;
    float x2=4.0;
    float y2=3.0;
    augmentCAByValues(theCA, x1,y1);
    augmentCAByValues(theCA, x2,y2);
    float correlationValue = finishCorrelation(theCA);
    float expectedResult = (x1*y1+x2*y2)/sqrt((x1*x1+x2*x2)*(y1*y1+y2*y2));
    if(fabs(correlationValue - expectedResult) > 0.00001)
        return reportEnd(false, "incorrect result");
    return reportEnd(true, NULL);
}
bool testInitializeCA (void)
Initialize a correlation aggregate.
Definition at line 185 of file tests.c.
References allocateCA(), CorrelationAggregate::denominatorL, CorrelationAggregate::denominatorR, initializeCA(), CorrelationAggregate::numerator, reportEnd(), and reportStart().
Referenced by runTests(), testAugmentCAByValues(), and testFinishCorrelation().
{
    reportStart("initializeCA");
    CorrelationAggregate* pCA = allocateCA();
    initializeCA(pCA);
    if(pCA->numerator != 0) return reportEnd(false, "nonzero numerator");
    if(pCA->denominatorL != 0) return reportEnd(false, "nonzero Ldenom");
    if(pCA->denominatorR != 0) return reportEnd(false, "nonzero Rdenom");
    return reportEnd(true, NULL);
}
bool testInOrder (void)
Check if inputs are in desired order.
Definition at line 145 of file tests.c.
References inOrder(), reportEnd(), and reportStart().
Referenced by runTests().
{
    reportStart("inOrder");
    float before=5.0; //Currently sorting high-to-low
    float after=3.0;
    if(!inOrder(before, after)) return reportEnd(false, "false negative");
    if(inOrder(after, before)) return reportEnd(false, "false positive");
    return reportEnd(true, NULL);
}
bool testLoadAndSaveFieldTDV (void)
Definition at line 489 of file tests.c.
References Field::element, Field::fieldnum, makeFieldFromTDV(), makeRandomField(), reportEnd(), Field::samples, and saveFieldToTDV().
Referenced by testMakeFieldFromTDV(), and testSaveFieldToTDV().
{
    int samples = 10;
    Field* tfld = makeRandomField(samples);
    char* filename = "testMake.tdv";
    saveFieldToTDV(filename, tfld);
    Field* tfld2 = makeFieldFromTDV(filename);
    if(tfld->samples != tfld2->samples)
        return reportEnd(false, "sample size mismatch");
    if(tfld->fieldnum != tfld2->fieldnum)
        return reportEnd(false, "field num mismatch");
    for(int i=0; i<samples; i++)
    {
        for(int j=0; j<samples; j++)
        {
            if(tfld->element[i][j] != tfld2->element[i][j])
                return reportEnd(false, "element mismatch");
        }
    }
    return reportEnd(true, NULL);
}
bool testMakeFieldFromTDV (void)
Load a tab-delimited-value file into a Field.
Definition at line 517 of file tests.c.
References reportStart(), and testLoadAndSaveFieldTDV().
Referenced by runTests().
{
    reportStart("makeFieldFromTDV");
    return testLoadAndSaveFieldTDV();
}
bool testMakeLandscapeFromTDVs (void)
Definition at line 569 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//int files, const char* filename[]
    reportStart("makeLandscapeFromTDVs");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testMakeListFromField (void)
Flatten a 2D field to a 1D list.
Parameters:
theField Field data to flatten
Returns:
A List containing all the elements of theField
Side Effects:
Adds flattened list to theField for memoization.
Definition at line 604 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Field* theField
    reportStart("makeListFromField");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testMakeListFromLandscape (void)
Definition at line 613 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* theData
    reportStart("makeListFromLandscape");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testMakeListFromList (void)
Create a List by copying another list.
Definition at line 330 of file tests.c.
References List::count, List::data, List::isMeanValid, List::isSorted, makeListFromList(), makeTestList(), List::mean, reportEnd(), and reportStart().
Referenced by runTests().
{
    reportStart("makeListFromList");
    List* oldData = makeTestList();
    List* newData = makeListFromList(oldData);
    //displayList(oldData);
    //displayList(newData);
    if(oldData->count != newData->count) return reportEnd(false, "size mismatch");
    for(int i=0; i<oldData->count; i++)
    {
        if(fabs(oldData->data[i] - newData->data[i]) > 0.0001)
            return reportEnd(false, "data mismatch");
    }
    if(oldData->isSorted != newData->isSorted) return reportEnd(false, "sortV mismatch");
    if(oldData->isMeanValid != newData->isMeanValid) return reportEnd(false, "meanV mismatch");
    if(oldData->isMeanValid && (oldData->mean != newData->mean)) return reportEnd(false, "mean mismatch");
    return reportEnd(true, NULL);
}
bool testMakePerm (void)
Creates a permutation of a given size.
Definition at line 238 of file tests.c.
References allocateArrayOfInts(), Perm::index, makePerm(), reportEnd(), reportStart(), SEED_IDENTITY, Perm::size, and TEST_SEED.
Referenced by runTests(), and testModifyPermPermutify().
{
    reportStart("makePerm");
    int testSize=3;
    Perm* aPerm = makePerm(testSize, TEST_SEED);
    if(aPerm->size != testSize) return reportEnd(false, "wrong size");
    int* indices_found = allocateArrayOfInts(testSize);
    for(int i=0; i<testSize; i++)
    {
        indices_found[i]=0;
    }
    for(int i=0; i<testSize; i++)
    {
        indices_found[aPerm->index[i]]++;
    }
    for(int i=0; i<testSize; i++)
    {
        if(indices_found[i]<1)
            return reportEnd(false, "index skipped");
        if(indices_found[i]>1)
            return reportEnd(false, "index repeated");
    }
    aPerm = makePerm(testSize, SEED_IDENTITY);
    for(int i=0; i<testSize; i++)
    {
        if(aPerm->index[i] != i) return reportEnd(false, "identity fail");
    }
    return reportEnd(true, NULL);
}
bool testMakeRandomField (void)
Create a symmetric Field with random data.
Definition at line 469 of file tests.c.
References Field::element, makeRandomField(), reportEnd(), reportStart(), and Field::samples.
Referenced by runTests().
{
    reportStart("makeRandomField");
    int samples=10;
    Field* tfld = makeRandomField(samples);
    if(tfld->samples != samples) return reportEnd(false, "sample count");
    for(int i=0; i<samples; i++)
    {
        for(int j=0; j<i; j++)
        {
            if(tfld->element[i][j] != tfld->element[j][i])
                return reportEnd(false, "not symmetric");
        }
    }
    return reportEnd(true, NULL);
}
bool testMantelR (void)
Find correlation of two sets of fields.
Parameters:
theFieldSet DataSet containing base fields and permutation to use
theCA optional (NULL for auto) correlation aggregator
Returns:
correlation value between base fields
Definition at line 630 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* mPreserved, Landscape* mPermuted, CorrelationAggregate* theCA
    reportStart("mantelR");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testMantelRPartial (void)
Definition at line 638 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* mPermuted,    Landscape* mPreserved,     Landscape* mGiven,    CorrelationAggregate* theCA
    reportStart("mantelRPartial");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testModifyLandscapeMeanify (void)
Definition at line 578 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* theData
    reportStart("modifyLandscapeMeanify");
    return reportFake();
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testModifyLandscapeRankify (void)
Definition at line 588 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//Landscape* theData
    reportStart("modifyLandscapeRankify");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testModifyListMeanify (void)
Center a list about its mean.
Definition at line 386 of file tests.c.
References List::count, List::data, List::isMeanValid, makeTestList(), List::mean, modifyListMeanify(), reportEnd(), and reportStart().
Referenced by runTests().
{
    reportStart("modifyListMeanify");
    List* theData = makeTestList();
    modifyListMeanify(theData);
    float theSum = 0;
    if(!(theData->isMeanValid)) return reportEnd(false, "mean not valid");
    if(fabs(theData->mean) > 0.0001) return reportEnd(false, "mean not zero");
    for(int i=0; i<theData->count; i++)
    {
        theSum += theData->data[i];
    }
    if(fabs(theSum) > 0.0001) return reportEnd(false, "mean miscalculated");
    return reportEnd(true, NULL);
}
bool testModifyListSortify (void)
Sort a list (heapsort)
Definition at line 405 of file tests.c.
References List::count, List::data, inOrder(), List::isSorted, makeTestList(), List::mean, modifyListSortify(), reportEnd(), and reportStart().
Referenced by runTests().
{
    reportStart("modifyListSortify");
    List* theData = makeTestList();
//    displayList(theData);
    modifyListSortify(theData);
//    displayList(theData);
    if(!(theData->isSorted)) return reportEnd(false, "sort not valid");
    if(fabs(theData->mean) > 0.0001) return reportEnd(false, "mean not zero");
    float lo, hi;
    for(int i=0; i<theData->count-1; i++)
    {
        lo = theData->data[i];
        hi = theData->data[i+1];
        //Sorting algorithm gives lists in reverse order
        if(!inOrder(hi, lo))
        {
            return reportEnd(false, "out of order");
        }
    }
    return reportEnd(true, NULL);
}
bool testModifyPermPermutify (void)
Change a permutation.
Definition at line 280 of file tests.c.
References Perm::index, makePerm(), modifyPermPermutify(), reportEnd(), reportStart(), SEED_IDENTITY, TEST_SEED, and testMakePerm().
Referenced by runTests().
{
    assert(testMakePerm());
    reportStart("modifyPermPermutify");
    int testSize = 5;
    Perm* thePerm = makePerm(testSize, SEED_IDENTITY);
    //showPermutation(thePerm);
    for(int i=0; i<testSize; i++)
    {
        if(thePerm->index[i] != i) return reportEnd(false, "pre-identity fail");
    }
    for(int i=0; i<testSize-1; i++)
    {
        modifyPermPermutify(thePerm, TEST_SEED);
        //showPermutation(thePerm);
    }   //Should result in identity
    for(int i=0; i<testSize; i++)
    {
        if(thePerm->index[i] != i) return reportEnd(false, "post-identity fail");
    }
    modifyPermPermutify(thePerm, TEST_SEED); //Mess it up once
    int displacements=0;
    for(int i=0; i<testSize; i++)
    {
        if(thePerm->index[i] != i) displacements++;
    }
    if(displacements<1) return reportEnd(false, "nonidentity fail");
    return reportEnd(true, NULL);
}
bool testProcessFilePairs (void)
Creates files containing data on Spearman and Person correlation of inputs.
Parameters:
trials Number of permutations to correlate for each type
filepairs Number of substrata that will be supplied
argv Array of (original) command-line arguments.
timestamp Time used for random seed, and to put in filenames
Side Effects:
Creates testinfo.TIMESTAMP.[Pearson|Spearman].[txt|tdv] files.
Definition at line 681 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//int trials, int filesets, const char* argv[], int timestamp
    reportStart("processFilePairs");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testProcessFileTriples (void)
Definition at line 690 of file tests.c.
References reportEnd(), reportFake(), and reportStart().
Referenced by runTests().
{//int trials, int filesets, const char* argv[], int timestamp
    reportStart("processFileTriples");
    return reportFake();
    return reportEnd(false, "STUB");
    return reportEnd(true, NULL);
}
bool testRandInRange (void)
Generate random number in a given range.
Definition at line 128 of file tests.c.
References randInRange(), reportEnd(), and reportStart().
Referenced by runTests().
{
    reportStart("randInRange");
    int numtests=10000;
    int rand;
    int low, high;
    low = 14;
    high = 99;
    for(int i=0; i<numtests; i++)
    {
        rand = randInRange(low, high);
        if(rand<low) return reportEnd(false, "too low");
        if(rand>high) return reportEnd(false, "too high");
    }
    return reportEnd(true, NULL);
}
bool testSaveFieldToTDV (void)
Save field data to file.
Definition at line 522 of file tests.c.
References reportStart(), and testLoadAndSaveFieldTDV().
Referenced by runTests().
{
    reportStart("saveFieldToTDV");
    return testLoadAndSaveFieldTDV();
}
bool testSaveListToTDV (void)
Output a list to file.
Definition at line 370 of file tests.c.
References makeTestList(), reportEnd(), reportStart(), and saveListToTDV().
{
    reportStart("saveListToTDV");
    saveListToTDV("testSave.tdv", makeTestList());
    printf("USER: please check testSave.tdv. Is it ok?");
    char answer='w';
    while(answer!='Y' && answer!='N')
    {
        printf(" Y/N: ");
        scanf(" %c", &answer);
    }
    return reportEnd(answer=='Y', "User rejected");
}
bool testSwapF (void)
Exchange contents of two float variables.
Definition at line 155 of file tests.c.
References reportEnd(), reportStart(), and swapF().
Referenced by runTests().
{
    reportStart("swapF");
    float lbefore,lafter,rbefore,rafter;
    lbefore = 3.0;
    rbefore = 5.0;
    lafter = lbefore;
    rafter = rbefore;
    swapF(&lafter, &rafter);
    if(lbefore != rafter) return reportEnd(false, "left not moved");
    if(rbefore != lafter) return reportEnd(false, "right not moved");
    return reportEnd(true, NULL);
}
bool testSwapI (void)
Exchange contents of two int variables.
Definition at line 169 of file tests.c.
References reportEnd(), reportStart(), and swapI().
Referenced by runTests().
{
    reportStart("swapI");
    int lbefore,lafter,rbefore,rafter;
    lbefore = 3;
    rbefore = 5;
    lafter = lbefore;
    rafter = rbefore;
    swapI(&lafter, &rafter);
    if(lbefore != rafter) return reportEnd(false, "left not moved");
    if(rbefore != lafter) return reportEnd(false, "right not moved");
    return reportEnd(true, NULL);
}